//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás bejelentkezési adatok!.
        /// </summary>
        public static string Error_BadCredentials {
            get {
                return ResourceManager.GetString("Error_BadCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EverlightApp.
        /// </summary>
        public static string General_AppDataDirectory {
            get {
                return ResourceManager.GetString("General_AppDataDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibás lekérdezés.
        /// </summary>
        public static string General_BadQuery {
            get {
                return ResourceManager.GetString("General_BadQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everlight.
        /// </summary>
        public static string General_CompanyName {
            get {
                return ResourceManager.GetString("General_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el.db.
        /// </summary>
        public static string General_DbName {
            get {
                return ResourceManager.GetString("General_DbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nincs találat.
        /// </summary>
        public static string General_NoResult {
            get {
                return ResourceManager.GetString("General_NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jelszó.
        /// </summary>
        public static string General_Password {
            get {
                return ResourceManager.GetString("General_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sikeres bejelentkezés!.
        /// </summary>
        public static string General_SuccessfulLogin {
            get {
                return ResourceManager.GetString("General_SuccessfulLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felhasználónév.
        /// </summary>
        public static string General_Username {
            get {
                return ResourceManager.GetString("General_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceConsoleApp.
        /// </summary>
        public static string ServiceConsole_AppName {
            get {
                return ResourceManager.GetString("ServiceConsole_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üdvözöllek {0} ({1})!.
        /// </summary>
        public static string ServiceConsole_Greeting {
            get {
                return ResourceManager.GetString("ServiceConsole_Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hibabejelentések lekérdezése (irányítószámok: 9999 | kerületek: 1xx | napok &lt;100) - {0}: kilépés.
        /// </summary>
        public static string ServiceConsole_Info {
            get {
                return ResourceManager.GetString("ServiceConsole_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to q.
        /// </summary>
        public static string ServiceConsole_Quit {
            get {
                return ResourceManager.GetString("ServiceConsole_Quit", resourceCulture);
            }
        }
    }
}
